package wiki_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/emgiezet/llmwiki/internal/wiki"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// writeKnowledge drops a raw file into <root>/knowledge/<layer>/<name>.
func writeKnowledge(t *testing.T, root, layer, name, content string) {
	t.Helper()
	dir := filepath.Join(root, wiki.KnowledgeDir, layer)
	require.NoError(t, os.MkdirAll(dir, 0755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, name), []byte(content), 0644))
}

func TestSearchKnowledge_ReturnsLayersInCallerOrder(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "auth.md", "# Auth Standard\n\nAll services use OIDC.\n")
	writeKnowledge(t, root, "platform-team", "deploy.md", "# Deploy\n\nArgoCD, one app per service.\n")

	store := wiki.NewStore(root)

	got, err := store.SearchKnowledge([]string{"platform-team", "global"}, "")
	require.NoError(t, err)
	require.Len(t, got, 2)
	assert.Equal(t, "platform-team", got[0].Layer, "caller's first layer must come first")
	assert.Equal(t, "global", got[1].Layer)

	// Reversing the caller's list reverses the results — order is priority.
	got, err = store.SearchKnowledge([]string{"global", "platform-team"}, "")
	require.NoError(t, err)
	require.Len(t, got, 2)
	assert.Equal(t, "global", got[0].Layer)
	assert.Equal(t, "platform-team", got[1].Layer)
}

func TestSearchKnowledge_AlphabeticalWithinLayer(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "zebra.md", "# Zebra\n")
	writeKnowledge(t, root, "global", "alpha.md", "# Alpha\n")
	writeKnowledge(t, root, "global", "middle.md", "# Middle\n")

	got, err := wiki.NewStore(root).SearchKnowledge([]string{"global"}, "")
	require.NoError(t, err)
	require.Len(t, got, 3)
	assert.Equal(t, []string{"alpha", "middle", "zebra"},
		[]string{got[0].Topic, got[1].Topic, got[2].Topic})
}

func TestSearchKnowledge_HandDroppedFileWithoutFrontMatter(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "adr-001.md", "# Use Postgres\n\nWe picked Postgres over Mongo.\n")

	got, err := wiki.NewStore(root).SearchKnowledge([]string{"global"}, "")
	require.NoError(t, err)
	require.Len(t, got, 1)
	assert.Equal(t, "adr-001", got[0].Topic)
	assert.Equal(t, "Use Postgres", got[0].Title, "title comes from the first H1")
	assert.Contains(t, got[0].Body, "We picked Postgres over Mongo.")
	assert.Equal(t, filepath.Join("knowledge", "global", "adr-001.md"), got[0].Path)
}

func TestSearchKnowledge_StripsFrontMatterFromBody(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "ingested.md",
		"---\nname: ingested\ntype: knowledge\n---\n\n## Summary\n\nGenerated by ingest.\n")

	got, err := wiki.NewStore(root).SearchKnowledge([]string{"global"}, "")
	require.NoError(t, err)
	require.Len(t, got, 1)
	assert.NotContains(t, got[0].Body, "type: knowledge", "front matter must not leak into the body")
	assert.Contains(t, got[0].Body, "Generated by ingest.")
	assert.Equal(t, "ingested", got[0].Title, "no H1 — falls back to the topic")
}

func TestSearchKnowledge_MissingLayerDirIsNotAnError(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "auth.md", "# Auth\n")

	got, err := wiki.NewStore(root).SearchKnowledge([]string{"global", "nonexistent"}, "")
	require.NoError(t, err, "an unpopulated layer is normal, not an error")
	require.Len(t, got, 1)
	assert.Equal(t, "global", got[0].Layer)
}

func TestSearchKnowledge_NoKnowledgeDirAtAll(t *testing.T) {
	got, err := wiki.NewStore(t.TempDir()).SearchKnowledge([]string{"global"}, "")
	require.NoError(t, err)
	assert.Empty(t, got)
}

func TestSearchKnowledge_NoLayersRequestedReturnsNothing(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "auth.md", "# Auth\n")

	got, err := wiki.NewStore(root).SearchKnowledge(nil, "")
	require.NoError(t, err)
	assert.Empty(t, got, "no layers requested = nothing to read")
}

func TestSearchKnowledge_MatchesTopicTitleAndBody(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "oidc-setup.md", "# Identity\n\nKeycloak realms per tenant.\n")
	writeKnowledge(t, root, "global", "billing.md", "# Billing\n\nStripe webhooks.\n")

	store := wiki.NewStore(root)
	layers := []string{"global"}

	for _, tc := range []struct{ name, query, wantTopic string }{
		{"matches topic", "oidc", "oidc-setup"},
		{"matches title", "identity", "oidc-setup"},
		{"matches body", "keycloak", "oidc-setup"},
		{"case insensitive", "STRIPE", "billing"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := store.SearchKnowledge(layers, tc.query)
			require.NoError(t, err)
			require.Len(t, got, 1)
			assert.Equal(t, tc.wantTopic, got[0].Topic)
		})
	}

	got, err := store.SearchKnowledge(layers, "definitely-not-present")
	require.NoError(t, err)
	assert.Empty(t, got)
}

func TestSearchKnowledge_SkipsGitDirAndNonMarkdown(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "auth.md", "# Auth\n")
	writeKnowledge(t, root, "global", "notes.txt", "not markdown")
	// A submodule checkout leaves a .git directory full of files inside the layer.
	gitDir := filepath.Join(root, wiki.KnowledgeDir, "global", ".git")
	require.NoError(t, os.MkdirAll(gitDir, 0755))
	require.NoError(t, os.WriteFile(filepath.Join(gitDir, "COMMIT_EDITMSG.md"), []byte("# nope\n"), 0644))

	got, err := wiki.NewStore(root).SearchKnowledge([]string{"global"}, "")
	require.NoError(t, err)
	require.Len(t, got, 1)
	assert.Equal(t, "auth", got[0].Topic)
}

func TestSearchKnowledge_ReadsNestedSubdirectories(t *testing.T) {
	root := t.TempDir()
	nested := filepath.Join(root, wiki.KnowledgeDir, "global", "adr")
	require.NoError(t, os.MkdirAll(nested, 0755))
	require.NoError(t, os.WriteFile(filepath.Join(nested, "001-postgres.md"), []byte("# Postgres\n"), 0644))

	got, err := wiki.NewStore(root).SearchKnowledge([]string{"global"}, "")
	require.NoError(t, err)
	require.Len(t, got, 1)
	assert.Equal(t, "001-postgres", got[0].Topic)
	assert.Equal(t, filepath.Join("knowledge", "global", "adr", "001-postgres.md"), got[0].Path)
}

func TestSearchKnowledge_RefusesSymlinkedEntry(t *testing.T) {
	root := t.TempDir()
	secret := filepath.Join(root, "secret.md")
	require.NoError(t, os.WriteFile(secret, []byte("# Secret\n"), 0644))
	layerDir := filepath.Join(root, wiki.KnowledgeDir, "global")
	require.NoError(t, os.MkdirAll(layerDir, 0755))
	if err := os.Symlink(secret, filepath.Join(layerDir, "leak.md")); err != nil {
		t.Skip("symlinks not supported:", err)
	}
	writeKnowledge(t, root, "global", "real.md", "# Real\n")

	got, err := wiki.NewStore(root).SearchKnowledge([]string{"global"}, "")
	require.NoError(t, err, "a symlink is skipped, not fatal")
	require.Len(t, got, 1)
	assert.Equal(t, "real", got[0].Topic)
}

func TestSearchKnowledge_RejectsUnsafeLayerName(t *testing.T) {
	root := t.TempDir()
	for _, bad := range []string{"..", "../etc", "a/b", ""} {
		_, err := wiki.NewStore(root).SearchKnowledge([]string{bad}, "")
		assert.Error(t, err, "layer %q must be rejected", bad)
	}
}

func TestGetKnowledge_ReturnsEntry(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "auth.md", "# Auth Standard\n\nOIDC via Keycloak.\n")

	got, err := wiki.NewStore(root).GetKnowledge("global", "auth")
	require.NoError(t, err)
	assert.Equal(t, "global", got.Layer)
	assert.Equal(t, "auth", got.Topic)
	assert.Equal(t, "Auth Standard", got.Title)
	assert.Contains(t, got.Body, "OIDC via Keycloak.")
}

func TestGetKnowledge_NotFound(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "auth.md", "# Auth\n")

	store := wiki.NewStore(root)

	_, err := store.GetKnowledge("global", "missing")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "missing")

	_, err = store.GetKnowledge("no-such-layer", "auth")
	require.Error(t, err)
}

func TestGetKnowledge_FindsTopicInNestedSubdirectory(t *testing.T) {
	root := t.TempDir()
	nested := filepath.Join(root, wiki.KnowledgeDir, "global", "adr")
	require.NoError(t, os.MkdirAll(nested, 0755))
	require.NoError(t, os.WriteFile(filepath.Join(nested, "001-postgres.md"), []byte("# Postgres\n"), 0644))

	got, err := wiki.NewStore(root).GetKnowledge("global", "001-postgres")
	require.NoError(t, err)
	assert.Equal(t, "001-postgres", got.Topic)
}

func TestGetKnowledge_RejectsUnsafeArguments(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "global", "auth.md", "# Auth\n")
	store := wiki.NewStore(root)

	_, err := store.GetKnowledge("../..", "auth")
	assert.Error(t, err, "traversal in layer must be rejected")

	_, err = store.GetKnowledge("global", "../../secret")
	assert.Error(t, err, "traversal in topic must be rejected")
}

func TestListKnowledgeLayers(t *testing.T) {
	root := t.TempDir()
	writeKnowledge(t, root, "platform-team", "deploy.md", "# Deploy\n")
	writeKnowledge(t, root, "global", "auth.md", "# Auth\n")
	// A stray file directly under knowledge/ is not a layer.
	require.NoError(t, os.WriteFile(filepath.Join(root, wiki.KnowledgeDir, "stray.md"), []byte("# Stray\n"), 0644))
	// Hidden/VCS directories are not layers either.
	require.NoError(t, os.MkdirAll(filepath.Join(root, wiki.KnowledgeDir, ".git"), 0755))

	got, err := wiki.NewStore(root).ListKnowledgeLayers()
	require.NoError(t, err)
	assert.Equal(t, []string{"global", "platform-team"}, got, "sorted, dirs only, no dotdirs")
}

func TestListKnowledgeLayers_NoKnowledgeDir(t *testing.T) {
	got, err := wiki.NewStore(t.TempDir()).ListKnowledgeLayers()
	require.NoError(t, err)
	assert.Empty(t, got)
}
